apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: nginx
    type: front-end
spec:
  template:
    metadata:
      name: mypod-app
      labels:
        app: app1
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end